### ISSUE TITLE
math equations not working

### ISSUE THREAD

**Issue by championswimmer** [coding-blocks/blog.codingblocks.com#5]

**Comment by adarsh1021** [comment]
Hello ! I was going through the blog.
Math equations for what and where exactly ?

**Comment by mubaris** [comment]
There are no math equations on the blog.

**Comment by 0xnmn** [comment]
Working very well locally; without any changes in the code. 

MD(used) -> `$$2\times A\times S_o = U\times T + \frac{A\times T^2}{2}$$`

![image](https://cloud.githubusercontent.com/assets/22571395/26141098/cbe3c538-3af7-11e7-8399-4e9108de9b77.png)

**Comment by AnshulMalik** [comment]
I think @championswimmer, you should at least give some hint about the issue, this isn't good at all, writing one line and let the people figure out by themselves.

**Comment by championswimmer** [comment]
actually this wasn't working previously. 
https://github.com/coding-blocks/blog.codingblocks.com/blob/gh-pages/_posts/2017-02-20-modelling-environments-in-netlogo-for-intelligent-agents.md
Seems it is all good. closing
